// Generated by alg3
`timescale 1ns/10ps
typedef struct packed {
  reg [6:0] funct7;
  reg [4:0] rs2;
  reg [4:0] rs1;
  reg [2:0] funct3;
  reg [4:0] rd;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Rtype;
typedef struct packed {
  reg [11:0] imm12;
  reg [4:0] rs1;
  reg [2:0] funct3;
  reg [4:0] rd;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Itype;
typedef struct packed {
  reg [6:0] imm11_5;
  reg [4:0] rs2;
  reg [4:0] rs1;
  reg [2:0] funct3;
  reg [4:0] imm4_0;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Stype;
typedef struct packed {
  reg [6:0] imm12_10_5;
  reg [4:0] rs2;
  reg [4:0] rs1;
  reg [2:0] funct3;
  reg [4:0] imm4_1_11;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Btype;
typedef struct packed {
  reg [19:0] imm31_12;
  reg [4:0] rd;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Utype;
typedef struct packed {
  reg [19:0] imm20_10_1_11_19_12;
  reg [4:0] rd;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Jtype;
typedef union packed {
  Rtype R;
  Itype I;
  Stype S;
  Btype B;
  Utype U;
  Jtype J;
  reg [31:0] raw;
 } iunion;
