#!/usr/bin/csh
set LOG_LOCATION="/home/016648840/EE297b/prj"
source /apps/design_environment.csh
setenv UVM_HOME /home/morris/uvm-1.2
vcs -sverilog -timescale=1ns/1ns -lca -cm line -cm_cond allops+for+full -cm_count +acc +vpi +define+UVM_OBJECT_MUST_HAVE_CONSTRUCTOR +incdir+${UVM_HOME}/src ${UVM_HOME}/src/uvm.sv ${UVM_HOME}/src/dpi/uvm_dpi.cc -CFLAGS -DVCS $argv
if ($status != 0) exit $status
./simv -cm line -cm_count | tee "${LOG_LOCATION}/logbook.log" #-a
if ($status != 0) exit $status
urg -lca -metric group+line -dir simv.vdb
if ($status != 0) exit $status
#bsub -l urg -report merge_rpt -dbname merge.vdb -f list_vdb
urg -f list_vdb -map merge.vdb
#firefox urgReport/dashboard.html
